[workspace]
resolver = "2"
members = [
    "common",
    "host",
    "host/examples/cpal",
    "plugin",
    "plugin/examples/gain",
    "plugin/examples/polysynth",
    "extensions",
    "test-host"
]

[workspace.dependencies]
clack-common = { path = "./common", version = "0.1.0" }
clack-plugin = { path = "./plugin", version = "0.1.0" }
clack-host = { path = "./host", version = "0.1.0", default-features = false }
clack-extensions = { path = "./extensions", version = "0.1.0" }
clack-test-host = { path = "./test-host", version = "0.1.0" }

clap-sys = "0.4.0"

bitflags = "2.4.2"
libloading = "0.8.1"
raw-window-handle_05 = { package = "raw-window-handle", version = "0.5.2" }
raw-window-handle_06 = { package = "raw-window-handle", version = "0.6.0" }
stable_deref_trait = "1.2.0"
