[package]
name = "clack-common"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap-sys = { git = "https://github.com/robbert-vdh/clap-sys.git", branch="update/clap-1.1.0" }
bitflags = "1.3.2"
