[package]
name = "clap-discovery"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs-sys = "0.5.0"
walkdir = "2.5.0"

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
objc2-foundation = { version = "0.3.2", features = ["NSBundle", "NSURL"] }

[lints]
workspace = true
